### PR TITLE
make a few tweaks to styling, check for consistency

### PR DESCRIPTION
**Pull request by ilikescience**
@shannonbyrne based on your feedback:

screen shot 2016-08-21 at 1 11 09 pm
screen shot 2016-08-21 at 1 12 55 pm
screen shot 2016-08-21 at 1 13 05 pm

lmk what you think, merge if 👍

 @alisdair feel free to double-check the code!

### CODE REVIEW

**Comment by alisdair** [comment]
@ilikescience Tests are failing here because they broke in #16; if you merge master into this branch, it'll pass 👍

**Comment by ilikescience** [comment]
@alisdair could I just rebase, or would you prefer a merge?

**Comment by alisdair** [comment]
Rebase is fine! I have no preference.

**Comment by ilikescience** [comment]
@alisdair 🎉

**Comment by shannonbyrne** [comment]
@ilikescience you know i don't know how to internet! is this ready to be merged?

**Pull request merged**
