### PR TITLE
alter song email styling to more closely match current styling

### PR DESCRIPTION
**Pull request by ilikescience**
@alisdair hi! I'd love to test this myself, but after getting this up and running locally, I wasn't able to log in.

Here's what I'm _generally_ going for:
screen shot 2016-08-20 at 3 21 56 pm

Please review, and let me know if I totally got everything wrong.

### CODE REVIEW

**Comment by alisdair** [comment]
Hey Matthew! Thanks for this PR. It made me notice that I broke the song email this week and didn't notice (😱). I've fixed those bugs and merged master into your branch, hope that's ok.

Some of your changes work fine, but the button change isn't quite right yet. I don't think it's going to be easy to achieve the exact old layout with the new template.

With this template, the button block has to be at the same level as the other blocks in the email, so that it works responsively from desktop to mobile. If you move it inside the other block, the layouts break a bit.

Here are screenshots of the current email layout at desktop and mobile widths:

master-desktop
master-mobile

And here's your changes:

new-desktop
new-mobile

You should be able to view test emails at http://localhost:3000/rails/mailers/subscription_mailer/song (or equivalent, depending on how you run the Rails app).

**Comment by ilikescience** [comment]
@alisdair thanks for the info! I'll get that button change fixed up right away.

**Comment by ilikescience** [comment]
@alisdair looks like that route would work if I had anything in the db; I get a page titled `ActiveRecord::RecordNotFound in Rails::MailersController#preview` from rails. What's the best way to get a few songs in the DB?

**Comment by alisdair** [comment]
@ilikescience Argh, sorry about the lack of set-up instructions. I'm going to work on some DB seeds shortly to make it easier, but for now:

1. Sign up for a new account locally. You should get a fake email opening in your browser via [letter_opener](https://github.com/ryanb/letter_opener)
2. Log out, then sign in as shannon@asongaday.co (default admin)
3. Go to "Curate" and add a song to the random queue, same way as normal

If that fails, you can do something like this in the Rails console

```
user = User.create!(name: 'Name', email: 'test12345@example.com')
Curator.random.subscriptions.create!(user: user)
Curator.random.songs.create!(url: 'https://www.youtube.com/watch?v=kk0WRHV_vt8', title: 'Song title', description: 'Description')
```

**Comment by ilikescience** [comment]
@alisdair awesome! Everything worked swimmingly. Letter opener is rad.

Updated things a bit — lmk what you think.

**Comment by alisdair** [comment]
Works for me!

**Comment by ilikescience** [comment]
Cool! I'll leave the merging to you.

**Comment by alisdair** [comment]
Technically ready to merge, but I'd rather leave the final decision on style to @shannonbyrne 😀

Couple of screenshots of these latest tweaks for reference:

Desktop: https://cloud.githubusercontent.com/assets/68917/17834174/1d354bd2-672c-11e6-9c7b-5d3070c68e88.png

Mobile: https://cloud.githubusercontent.com/assets/68917/17834175/1d51d3b0-672c-11e6-9946-43a4e0b4e2da.png

**Comment by shannonbyrne** [comment]
Hey @ilikescience - I know I approved, but looking at it again, can we un-italicise the song name text? And maybe add just one light shade of grey as a top bar/header and one at the bottom/footer? I like the white but just to break it up a bit? 

If you think it will look bad just let me know! 

I know we want it to look similar but I don't think they'll care if the font looks a lil different. 

Thank you!

**Comment by shannonbyrne** [comment]
All of that said, I'm going to merge this now so it goes live tmrw. we can make the other changes later. :)

**Pull request merged**
